---
output: html_document
---

```{r, echo=F}
title_var <- "Lampros Bouranis - About"
```    
---
title: `r title_var`
---

<link rel="stylesheet" href="styles.css" type="text/css">

<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-51103728-2"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-51103728-2');
</script>

<style>
.title {
    display: none
  }
</style>

## Professional Experience

**May. 2021 -- June 2023** Marie Sklodowska-Curie Research Fellow,\
Department of Statistics, *Athens University of Economics and Business*, Greece

**Mar. 2019 -- Apr. 2021** Statistician -- Data Science Consultant,\
Accenture Greece, Athens

**Jan. 2014 -- Jan. 2018** PhD Researcher in Statistics,\
School of Mathematics and Statistics, *University College Dublin*, Ireland

**Oct. 2012 -- Dec. 2013** Medical Applied Statistician,\
Cardiovascular Epidemiology Unit, Department of Public Health and Primary Care, *University of Cambridge*, UK

**Jun. 2012 -- Sept. 2012** MSc Researcher,\
Paterson Institute for Cancer Research, *The Christie NHS Foundation*, Manchester, UK


## Education
**2018**  PhD in Statistics\
*University College Dublin*, Ireland  
          
**2012**  MSc in Statistics\
*Lancaster University*, UK 
          
**2011**  BSc in Statistics \
*Athens University of Economics and Business*, Greece

## Compulsory national service
**Mar. 2018 -- Mar. 2019** Airman at Hellenic Air Force (HAF).

## Awards
**2021** Marie Sklodowska-Curie Individual Fellowship - BERNADETTE: "Bayesian inference and model selection for stochastic epidemics". European Union’s Horizon 2020 research and innovation programme under the Marie Sklodowska-Curie grant agreement No 101027218.

**2019** [Seal of Excellence](Seal_of_Excellence_838594_BERNADETTE.pdf) of the European Commission for the project proposal "Bayesian inference and model selection for stochastic epidemics" (proposal number: 838594). Host institution: Athens University of Economics and Business (Greece). Call: Horizon 2020’s Marie Sklodowska-Curie Actions 2018 (H2020-MSCA-IF-2018). Evaluation: the project proposal was scored as a high-quality project proposal in a highly competitive evaluation process.

**2016** Best poster presentation at CASI 2016: 36th Conference on Applied Statistics in Ireland, Limerick (May 2016).

**2014** Insight Centre for Data Analytics Doctoral training Studentship.

**2010** Awarded with honorary scholarship from The State Scholarships Foundation of Greece for the academic year 2009-2010.

**2009** Awarded with honorary scholarship from The State Scholarships Foundation of Greece for the academic year 2008-2009.


## Reviewing activity
PLOS ONE

Journal of Computational and Graphical Statistics

IEEE Transactions on Network Science and Engineering

International Conference on Artificial Intelligence and Statistics (AISTATS)

## Associations
American Statistical Association

Irish Statistical Association

International Network for Social Network Analysis

Royal Statistical Society